flowchart TD

    A[" Gérer les catégories"]

    B["Tâche 1 : Créer le MCD"]
    C["Tâche 2 : Créer la base de données"]
    D["Tâche 3 : Créer le CRUD API"]
    E["Tâche 4 : Créer le formulaire HTML"]
    F["Tâche 5 : Connecter l'API avec le formulaire"]
    G["Tâche 6 : Tester"]
    H["Tâche 7 : Valider"]

    A --> B
    B --> C
    C --> D
    D --> E
    E --> F
    F --> G
    G --> H